### ISSUE TITLE
Reject promise with NotSupportedError on unsupported keysystem in 'HDCP Policy Check' proposal

### ISSUE THREAD

**Issue by JamesWCCheng** [WICG/media-capabilities#56] opened 2017-11-10 08:19 UTC
If we use ``getStatusForPolicy`` API on ClearKey or any other unsupported keysystem,
should we reject the promise with ``NotSupportedError``?

Spec[1] only said that 
``If HDCP is available at the specified version, the promise should return a MediaKeyStatus of "usable". Otherwise, the promise should return a MediaKeyStatus of "output-restricted".``

I don't think it is reasonable to resolve a promise with output-restricted on the unsupported keysystem.

@xhwang-chromium , @mounirlamouri 

[1] https://github.com/WICG/media-capabilities/blob/master/eme-extension-policy-check.md

**Comment by mounirlamouri** [comment] 2017-11-10 10:56
By "unsupported keysystem" do you mean a key system not supported by the UA? In which case, `requestMediaKeySystemAccess()` should already throw `NotSupportedErorr` and you will not be allowed to call `getStatusForPolicy()`, right?

**Comment by JamesWCCheng** [comment] 2017-11-10 11:06
Sorry, I didn't describe precisely.

I mean the keysystem that did not implement this api. e.g. I create mediakeys with org.w3.clearkey  but clearkey has not implement this feauture yet. Should we reject the promise? If so, should we update the spec?

Thanks

**Comment by mounirlamouri** [comment] 2017-11-10 11:13
I think what matters the most is to properly reflect what the key system will do when asked for some limitations and I guess that's not specified... The issue is that if a key system doesn't detect HDCP but detect NewFeature, what should we do? I would tend to say that we should reflect what the key system would do: will it reject a request with the limitations applied? If a limitation is moot, somehow, it's `usable`, isn't it?

**Comment by JamesWCCheng** [comment] 2017-11-10 12:10
Yes, I agree.
But the spec didn't mention when this api should reject the promise.
Is it necessary to write into spec or browsers can determine by their own? 

Sorry, this is my first time participating spec discussion.
I jus want to know if all cases need to list down in spec.

Thanks

**Comment by xhwang-chromium** [comment] 2017-11-10 22:17
James: Good point. Yes, I think it makes that if a MediaKeys doesn't not support this policy check that it should reject the promise with NotSupportedError. This is actually how things are implemented in Blink/Chromium.

That being said, the current doc is more a explainer page than a full sepc, so many details and steps will need to be added.

**Comment by mounirlamouri** [comment] 2017-11-20 14:15
@xhwang-chromium do you think it is worth updating the explainer to address the issue or should we close it?

**Comment by mounirlamouri** [comment] 2017-12-07 13:49
@xhwang-chromium ping :)

**Comment by xhwang-chromium** [comment] 2017-12-07 18:08
Sorry for the delayed response. Yes, adding it to the explainer makes sense. But then I guess there are many detailed steps missing. Do we want to add more detailed steps so it looks more like a spec than a explainer doc?

**Comment by jyavenard** [comment] 2018-05-14 10:27
Since HDCP support report is moving to be part of EME, should this issue be closed now?

**Comment by mounirlamouri** [comment] 2018-05-15 10:59
Good call. Moved it here: https://github.com/WICG/hdcp-detection/issues/2

**Closed by mounirlamouri** 2018-05-15 10:59 UTC
Labels: HDCP

**Comment by joeyparrish** [comment] 2018-11-06 23:18
@JamesWCCheng, this does not make sense because the new method is on `MediaKeys`.  You can't get a `MediaKeys` instance if the key system is unsupported, so this error would have been reached during `requestMediaKeySystemAccess`.

(Cross-posted to the migrated issue as well.)
